(() => {
'use strict';
if(!document.body.classList.contains('locale-tr'))return;
const localAvatarCache=new Map();
const toastMap=new Map([
['TRACE THE WHOLE SHAPE','ŞEKLİN TAMAMINI İZLE'],['TRACE VERIFICATION FAILED','İZ DOĞRULAMASI BAŞARISIZ'],['TRACE UNAVAILABLE','İZ SÜR KULLANILAMIYOR'],['SIGN IN FIRST','ÖNCE GİRİŞ YAP'],['PROFILE SECURED','PROFİL KORUNDU'],['ACCOUNT CREATED','HESAP OLUŞTURULDU'],['SIGNED IN','GİRİŞ YAPILDI'],['PASSWORD UPDATED','ŞİFRE GÜNCELLENDİ'],['CREATING 60-SECOND DUEL','60 SANİYELİK DÜELLO OLUŞTURULUYOR'],['JOINING 60-SECOND DUEL','60 SANİYELİK DÜELLOYA KATILINIYOR'],['INVITE COPIED','DAVET KOPYALANDI'],['INVITE LINK COPIED','DAVET LİNKİ KOPYALANDI'],['SHARE UNAVAILABLE','PAYLAŞIM KULLANILAMIYOR'],['COPY UNAVAILABLE','KOPYALAMA KULLANILAMIYOR'],['LIVE ROOM UNAVAILABLE','CANLI ODA KULLANILAMIYOR'],['COULD NOT JOIN DUEL','DÜELLOYA KATILINAMADI'],['DUEL IS NOT ACTIVE','DÜELLO AKTİF DEĞİL']
]);
try{if(typeof showToast==='function'){const prev=showToast;showToast=function(msg,...a){return prev(toastMap.get(String(msg))||String(msg),...a)}}}catch{}
function fixDrawLabels(){
  const classic=document.querySelector('#classicButton span');
  if(classic && ['BERABERE','DRAW'].includes(classic.textContent.trim())) classic.textContent='ÇİZ';
  const live=document.getElementById('liveStatus');
  if(live && live.textContent.trim()==='BERABERE') live.textContent='ÇİZ';
  const trace=document.getElementById('traceLiveScore');
  if(trace && trace.textContent.trim()==='BERABERE') trace.textContent='ÇİZ';
}
function realName(label){const s=String(label||'').trim();if(s==='SEN'||s==='YOU')return typeof profile!=='undefined'?(profile?.username||''):'';if(['RAKİP','RIVAL','BEKLENİYOR…','WAITING…','HOST'].includes(s))return'';return s}
async function getAvatar(label){const name=realName(label);if(!name)return null;if(localAvatarCache.has(name))return localAvatarCache.get(name);try{const r=await fetch(`${config.supabaseUrl}/rest/v1/o_profiles?username=eq.${encodeURIComponent(name)}&select=avatar_url&limit=1`,{headers:{apikey:API_KEY}}),rows=await r.json(),url=rows?.[0]?.avatar_url||null;localAvatarCache.set(name,url);return url}catch{localAvatarCache.set(name,null);return null}}
async function paint(root,label){if(!root)return;const name=realName(label),span=root.querySelector('span'),img=root.querySelector('img');if(span)span.textContent=(name||'?').slice(0,1).toUpperCase();const url=await getAvatar(label);if(url&&img){img.src=url;img.classList.add('loaded')}else if(img){img.removeAttribute('src');img.classList.remove('loaded')}}
function repaintAvatars(){setTimeout(()=>{paint(document.querySelector('[data-duel-avatar="host"]'),document.getElementById('liveHostName')?.textContent);paint(document.querySelector('[data-duel-avatar="guest"]'),document.getElementById('liveGuestName')?.textContent);paint(document.querySelector('[data-hud-avatar="host"]'),document.getElementById('liveHudYouName')?.textContent);paint(document.querySelector('[data-hud-avatar="guest"]'),document.getElementById('liveHudRivalName')?.textContent)},120)}
function fixDynamic(){fixDrawLabels();const lobby=document.getElementById('liveLobbyCopy');if(lobby){let s=lobby.textContent.trim(),m;if((m=s.match(/^Draw · ([0-9.]+) vs ([0-9.]+) · No CROWN$/)))lobby.textContent=`Berabere · ${m[1]} - ${m[2]} · TAÇ yok`;else if((m=s.match(/^(.+) wins \+1 CROWN · ([0-9.]+)$/)))lobby.textContent=`${m[1]} kazandı · +1 TAÇ · ${m[2]}`}const rc=document.getElementById('liveRewardCopy');if(rc){let s=rc.textContent.trim(),m;if((m=s.match(/^CROWN #(\d+) added to your profile\.$/)))rc.textContent=`TAÇ #${m[1]} profiline eklendi.`;else if((m=s.match(/^(.+) earned the CROWN\.$/)))rc.textContent=`${m[1]} TAÇ kazandı.`}const verdict=document.getElementById('resultVerdict');if(verdict){let s=verdict.textContent.trim(),m;if((m=s.match(/^([0-9.]+)% from perfection\.$/)))verdict.textContent=`Kusursuzluktan %${m[1]} uzakta.`}}
const desc=new Map([['That should not be possible.','Bu mümkün olmamalıydı.'],['Almost no wasted motion.','Neredeyse kusursuz hareket.'],['A remarkably controlled curve.','Olağanüstü kontrollü bir eğri.'],['The circle barely resisted.','Daire neredeyse hiç direnmedi.'],['Your hand understands the curve.','Elin eğriyi anlıyor.'],['Controlled. Not perfect.','Kontrollü. Kusursuz değil.'],['The geometry is there.','Geometri yerinde.'],['Recognizable. Unforgiving.','Tanıdık. Ama affetmiyor.'],['Perfection was not consulted.','Kusursuzluğa danışılmadı.']]);for(const el of document.querySelectorAll('.verdict,.result-sheet p,.account-copy,.level-hub-copy')){const x=desc.get(el.textContent.trim());if(x)el.textContent=x}repaintAvatars()}
const targets=['classicButton','liveHostName','liveGuestName','liveHudYouName','liveHudRivalName','liveLobbyCopy','liveRewardCopy','resultVerdict','traceLiveScore'].map(id=>document.getElementById(id)).filter(Boolean);const mo=new MutationObserver(fixDynamic);targets.forEach(n=>mo.observe(n,{subtree:true,childList:true,characterData:true}));fixDynamic();setTimeout(fixDynamic,100);setTimeout(fixDynamic,500);setTimeout(fixDynamic,1200);
})();