(() => {
'use strict';
const TRACE_API=`${config.supabaseUrl||''}/functions/v1/o-trace`;
const TRACE_SCORE_API=`${config.supabaseUrl||''}/functions/v1/o-trace-score`;
let traceStatus=null,traceRun=null,tracePoints=[],traceDrawing=false,tracePointer=null,traceBusy=false,traceCtx=null,traceDpr=1;
const avatarCache=new Map();

async function traceEdge(action,payload={}){
  const r=await fetch(TRACE_API,{method:'POST',headers:{apikey:API_KEY,'Content-Type':'application/json'},body:JSON.stringify({action,installationId,installationSecret,...payload})});
  const text=await r.text();let data=null;if(text){try{data=JSON.parse(text)}catch{}}
  if(!r.ok){const e=new Error(data?.error||`Trace request failed (${r.status})`);e.status=r.status;throw e}return data;
}
function ensureTraceUI(){
  const practice=document.getElementById('modePractice')||document.querySelector('.home-actions');
  if(practice&&!document.getElementById('traceModeButton')){
    practice.insertAdjacentHTML('afterbegin','<button class="trace-mode-cta" id="traceModeButton" type="button"><span><b>TRACE</b><i>30 LEVELS</i></span><small id="traceHomeTarget">FOLLOW THE LINE · SERVER VERIFIED</small><em id="traceHomeLevel">LV. 01</em></button>');
    document.getElementById('traceModeButton').addEventListener('click',openTrace);
  }
  if(!document.getElementById('traceScreen'))document.body.insertAdjacentHTML('beforeend',`
    <section class="trace-screen" id="traceScreen" aria-hidden="true">
      <header class="trace-top"><button class="trace-back" id="traceBack" type="button">×</button><div class="trace-title"><span>PRECISION PATH</span><b>TRACE</b></div><div class="trace-meta"><span id="traceLevelLabel">LEVEL 01 / 30</span><b id="traceStarsLabel">★ 0</b></div></header>
      <canvas id="traceCanvas" aria-label="Trace the target shape"></canvas>
      <div class="trace-hint"><div><span>TARGET</span><b id="traceTargetLabel">70.00+</b></div><strong id="traceLiveScore">DRAW</strong></div>
    </section>
    <section class="trace-result" id="traceResult" aria-hidden="true"><span id="traceResultKicker">TRACE RESULT</span><h2><b id="traceResultScore">—</b><small>%</small></h2><strong id="traceResultState">FOLLOW THE PATH</strong><p id="traceResultCopy">Stay on the target line from start to finish.</p><div class="trace-metrics"><div><span>COVERAGE</span><b id="traceCoverage">—</b></div><div><span>DEVIATION</span><b id="traceDeviation">—</b></div></div><button id="traceNext" type="button">TRY SHAPE →</button></section>`);
  document.getElementById('traceBack')?.addEventListener('click',closeTrace);
  document.getElementById('traceNext')?.addEventListener('click',()=>{toggleTraceResult(false);startTrace()});
  const c=document.getElementById('traceCanvas');
  if(c&&!traceCtx){traceCtx=c.getContext('2d',{alpha:true,desynchronized:true});c.addEventListener('pointerdown',traceBegin,{passive:false});c.addEventListener('pointermove',traceMove,{passive:false});c.addEventListener('pointerup',traceEnd,{passive:false});c.addEventListener('pointercancel',traceEnd,{passive:false})}
  if(!document.getElementById('traceProfileCard')&&document.getElementById('profileScreen')){
    const anchor=document.getElementById('accountProfileCard')||document.querySelector('#profileScreen .profile-identity');
    anchor?.insertAdjacentHTML('afterend','<section class="trace-profile-card" id="traceProfileCard"><span>TRACE PROGRESSION</span><b id="traceProfileLevel">LEVEL 01 / 30</b><strong id="traceProfileStars">★ 0</strong><small id="traceProfileBest">BEST — · 0 BADGES</small></section>');
  }
  ensureDuelAvatars();
}
function toggleTrace(open=true){const s=document.getElementById('traceScreen');s?.classList.toggle('visible',open);s?.setAttribute('aria-hidden',open?'false':'true')}
function toggleTraceResult(open=true){const s=document.getElementById('traceResult');s?.classList.toggle('visible',open);s?.setAttribute('aria-hidden',open?'false':'true')}
function traceFrame(){const c=document.getElementById('traceCanvas'),r=c.getBoundingClientRect();return{w:r.width,h:r.height,cx:r.width/2,cy:r.height*.53,scale:Math.min(r.width*.38,r.height*.32)}}
function shapePoint(p,f){return{x:f.cx+Number(p[0])*f.scale,y:f.cy+Number(p[1])*f.scale}}
function resizeTrace(){const c=document.getElementById('traceCanvas');if(!c||!traceCtx)return;const r=c.getBoundingClientRect();traceDpr=Math.min(window.devicePixelRatio||1,2);c.width=Math.round(r.width*traceDpr);c.height=Math.round(r.height*traceDpr);traceCtx.setTransform(traceDpr,0,0,traceDpr,0,0);drawTrace()}
function drawTrace(){const c=document.getElementById('traceCanvas');if(!c||!traceCtx)return;const f=traceFrame();traceCtx.clearRect(0,0,f.w,f.h);if(traceRun?.shape?.length){const pts=traceRun.shape.map(p=>shapePoint(p,f));traceCtx.save();traceCtx.lineCap='round';traceCtx.lineJoin='round';traceCtx.beginPath();traceCtx.moveTo(pts[0].x,pts[0].y);for(let i=1;i<pts.length;i++)traceCtx.lineTo(pts[i].x,pts[i].y);traceCtx.strokeStyle='rgba(212,244,93,.12)';traceCtx.lineWidth=10;traceCtx.stroke();traceCtx.strokeStyle='rgba(212,244,93,.70)';traceCtx.lineWidth=1.35;traceCtx.setLineDash([5,6]);traceCtx.stroke();traceCtx.restore()}if(tracePoints.length>1){traceCtx.save();traceCtx.lineCap='round';traceCtx.lineJoin='round';traceCtx.strokeStyle='#f0ede5';traceCtx.lineWidth=2.35;traceCtx.beginPath();traceCtx.moveTo(tracePoints[0].x,tracePoints[0].y);for(let i=1;i<tracePoints.length;i++)traceCtx.lineTo(tracePoints[i].x,tracePoints[i].y);traceCtx.stroke();traceCtx.restore()}}
function pos(e){const r=document.getElementById('traceCanvas').getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top,t:performance.now()}}
function addTracePoint(p){const q=tracePoints[tracePoints.length-1];if(!q||Math.hypot(p.x-q.x,p.y-q.y)>=1.2)tracePoints.push(p)}
function traceBegin(e){if(!traceRun||traceBusy||traceDrawing)return;if(e.pointerType==='mouse'&&e.button!==0)return;e.preventDefault();traceDrawing=true;tracePointer=e.pointerId;tracePoints=[];document.getElementById('traceCanvas').setPointerCapture?.(e.pointerId);addTracePoint(pos(e));document.getElementById('traceLiveScore').textContent='TRACE';drawTrace();navigator.vibrate?.(6)}
function traceMove(e){if(!traceDrawing||e.pointerId!==tracePointer)return;e.preventDefault();addTracePoint(pos(e));drawTrace()}
async function traceEnd(e){if(!traceDrawing||e.pointerId!==tracePointer)return;e.preventDefault();addTracePoint(pos(e));traceDrawing=false;tracePointer=null;drawTrace();if(tracePoints.length<12)return showToast('TRACE THE WHOLE SHAPE');await submitTrace()}
async function submitTrace(){if(!traceRun||traceBusy)return;traceBusy=true;document.getElementById('traceLiveScore').textContent='VERIFYING…';try{const f=traceFrame(),r=await fetch(TRACE_SCORE_API,{method:'POST',headers:{apikey:API_KEY,'Content-Type':'application/json'},body:JSON.stringify({installationId,installationSecret,runId:traceRun.id,viewport:{width:+f.w.toFixed(2),height:+f.h.toFixed(2)},stroke:tracePoints.map(p=>({x:+p.x.toFixed(2),y:+p.y.toFixed(2),t:Math.round(p.t)}))})});const text=await r.text();let d=null;if(text){try{d=JSON.parse(text)}catch{}}if(!r.ok)throw new Error(d?.error||`Trace verification failed (${r.status})`);showTraceResult(d);await refreshTraceStatus()}catch(e){showToast(e?.message||'TRACE VERIFICATION FAILED');document.getElementById('traceLiveScore').textContent='RETRY'}finally{traceBusy=false}}
function showTraceResult(d){document.getElementById('traceResultKicker').textContent=d.passed?'LEVEL CLEARED':'TRACE RESULT';document.getElementById('traceResultScore').textContent=Number(d.score||0).toFixed(2);document.getElementById('traceResultState').textContent=d.passed?`+${Number(d.rewardStars||0)} STARS`:`NEED ${Number(d.targetScore||traceRun?.targetScore||0).toFixed(2)}+`;document.getElementById('traceResultCopy').textContent=d.badge?`${d.badge} unlocked.`:d.passed?`Level ${String(Math.min(30,Number(d.currentLevel||1))).padStart(2,'0')} is ready.`:'A new random shape will be generated for the same level.';document.getElementById('traceCoverage').textContent=`${Number(d.metrics?.coverage||0).toFixed(1)}%`;document.getElementById('traceDeviation').textContent=Number(d.metrics?.meanDeviation||0).toFixed(3);document.getElementById('traceNext').textContent=Number(d.currentLevel)>30?'COMPLETE →':d.passed?'NEXT LEVEL →':'NEW SHAPE →';toggleTraceResult(true);navigator.vibrate?.(d.passed?[30,30,65,35,105]:[45,35,45])}
async function startTrace(){toggleTraceResult(false);tracePoints=[];traceRun=null;document.getElementById('traceLiveScore').textContent='LOADING';try{const d=await traceEdge('start');if(d.complete){document.getElementById('traceLiveScore').textContent='COMPLETE';showToast('ALL TRACE LEVELS CLEARED');return}traceRun=d.run;document.getElementById('traceLevelLabel').textContent=`LEVEL ${String(traceRun.levelNo).padStart(2,'0')} / 30`;document.getElementById('traceTargetLabel').textContent=`${Number(traceRun.targetScore).toFixed(2)}+`;document.getElementById('traceLiveScore').textContent='DRAW';resizeTrace()}catch(e){showToast(e?.message||'TRACE UNAVAILABLE');closeTrace()}}
async function openTrace(){if(!profile)return showToast('SIGN IN FIRST');ensureTraceUI();toggleTrace(true);setTimeout(resizeTrace,30);await startTrace()}
function closeTrace(){traceDrawing=false;tracePointer=null;traceRun=null;tracePoints=[];toggleTraceResult(false);toggleTrace(false)}
async function refreshTraceStatus(){if(!profile)return;try{traceStatus=await traceEdge('status');renderTraceStatus()}catch{}}
function renderTraceStatus(){if(!traceStatus)return;const p=traceStatus.progress||{},complete=!!traceStatus.complete,lv=Number(p.current_level||1),stars=Number(p.stars||0),next=traceStatus.next,badges=traceStatus.badges||[];const home=document.getElementById('traceHomeLevel'),target=document.getElementById('traceHomeTarget');if(home)home.textContent=complete?'COMPLETE':`LV. ${String(lv).padStart(2,'0')}`;if(target)target.textContent=complete?'ALL 30 LEVELS CLEARED':`${Number(next?.targetScore||70).toFixed(2)}+ TARGET · RANDOM SHAPE`;const sl=document.getElementById('traceStarsLabel');if(sl)sl.textContent=`★ ${stars}`;const pl=document.getElementById('traceProfileLevel');if(pl)pl.textContent=complete?'30 / 30 COMPLETE':`LEVEL ${String(lv).padStart(2,'0')} / 30`;const ps=document.getElementById('traceProfileStars');if(ps)ps.textContent=`★ ${stars}`;const pb=document.getElementById('traceProfileBest');if(pb)pb.textContent=`BEST ${p.best_score==null?'—':Number(p.best_score).toFixed(2)} · ${badges.length} BADGES`}

function ensureDuelAvatars(){const cards=document.querySelectorAll('.live-versus article');cards.forEach((card,i)=>{if(card.querySelector('.live-avatar'))return;card.insertAdjacentHTML('afterbegin',`<div class="live-avatar" data-duel-avatar="${i?'guest':'host'}"><img alt=""><span>?</span></div>`)});const hud=document.getElementById('liveHud');if(hud){hud.querySelectorAll(':scope > div').forEach((box,i)=>{if(box.querySelector('.live-hud-avatar'))return;box.insertAdjacentHTML('afterbegin',`<div class="live-hud-avatar" data-hud-avatar="${i?'guest':'host'}"><img alt=""><span>?</span></div>`)})}watchDuelNames()}
async function avatarFor(name){const clean=String(name||'').trim();if(!clean||clean==='WAITING…'||clean==='RIVAL'||clean==='HOST')return null;const real=clean==='YOU'?(profile?.username||''):clean;if(!real)return null;if(avatarCache.has(real))return avatarCache.get(real);try{const r=await fetch(`${config.supabaseUrl}/rest/v1/o_profiles?username=eq.${encodeURIComponent(real)}&select=username,avatar_url&limit=1`,{headers:{apikey:API_KEY}}),rows=await r.json();const url=rows?.[0]?.avatar_url||null;avatarCache.set(real,url);return url}catch{avatarCache.set(real,null);return null}}
async function paintAvatar(root,name){if(!root)return;const real=String(name||'').trim()==='YOU'?(profile?.username||''):String(name||'').trim(),letter=(real||'?').slice(0,1).toUpperCase(),span=root.querySelector('span'),img=root.querySelector('img');if(span)span.textContent=letter;const url=await avatarFor(name);if(url&&img){img.src=url;img.classList.add('loaded')}else if(img){img.removeAttribute('src');img.classList.remove('loaded')}}
function updateDuelAvatars(){paintAvatar(document.querySelector('[data-duel-avatar="host"]'),document.getElementById('liveHostName')?.textContent);paintAvatar(document.querySelector('[data-duel-avatar="guest"]'),document.getElementById('liveGuestName')?.textContent);paintAvatar(document.querySelector('[data-hud-avatar="host"]'),document.getElementById('liveHudYouName')?.textContent);paintAvatar(document.querySelector('[data-hud-avatar="guest"]'),document.getElementById('liveHudRivalName')?.textContent)}
let duelObserver=null;function watchDuelNames(){if(duelObserver)return;const nodes=['liveHostName','liveGuestName','liveHudYouName','liveHudRivalName'].map(id=>document.getElementById(id)).filter(Boolean);if(!nodes.length)return;duelObserver=new MutationObserver(()=>updateDuelAvatars());nodes.forEach(n=>duelObserver.observe(n,{childList:true,characterData:true,subtree:true}));updateDuelAvatars()}

ensureTraceUI();window.addEventListener('resize',()=>{if(document.getElementById('traceScreen')?.classList.contains('visible'))resizeTrace()},{passive:true});
setTimeout(()=>{ensureTraceUI();refreshTraceStatus();updateDuelAvatars()},350);
if(typeof loadProfileStats==='function'){const lp=loadProfileStats;loadProfileStats=async function(...a){const out=await lp(...a);await refreshTraceStatus();return out}}
})();