export const TAU=Math.PI*2;export const clamp=(v,a=0,b=1)=>Math.min(b,Math.max(a,v));export const ease=t=>1-Math.pow(1-clamp(t),4);
export class DrawingRenderer{
  constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d',{alpha:true,desynchronized:true});this.points=[];this.analysis=null;this.pending=false;this.liveIndex=1;this.resize()}
  resize(){this.dpr=Math.min(devicePixelRatio||1,innerWidth<700?1.45:1.9);this.canvas.width=Math.floor(innerWidth*this.dpr);this.canvas.height=Math.floor(innerHeight*this.dpr);this.canvas.style.width=innerWidth+'px';this.canvas.style.height=innerHeight+'px';this.ctx.setTransform(this.dpr,0,0,this.dpr,0,0);this.liveIndex=1;if(this.analysis)this.drawResult();else if(this.points.length>1)this.redrawLive()}
  clear(){this.ctx.clearRect(0,0,innerWidth,innerHeight)} reset(){this.points=[];this.analysis=null;this.liveIndex=1;this.pending=false;this.clear()} start(p){this.points=[p];this.analysis=null;this.liveIndex=1;this.clear()}
  add(p){const q=this.points.at(-1);if(q&&Math.hypot(p.x-q.x,p.y-q.y)<.55)return;this.points.push(p);if(this.points.length>2200)this.points.splice(1,1);this.request()}
  request(){if(this.pending)return;this.pending=true;requestAnimationFrame(()=>{this.pending=false;this.drawNewSegments()})}
  segment(a,b){const c=this.ctx,dt=Math.max(2,b.t-a.t),speed=Math.hypot(b.x-a.x,b.y-a.y)/dt,s=clamp(speed/1.55),p=b.p||.5,w=(5.2-2.45*s)*(.88+.32*p);c.save();c.lineCap='round';c.lineJoin='round';c.globalCompositeOperation='source-over';c.strokeStyle='rgba(227,75,45,.13)';c.lineWidth=w+12;c.shadowColor='rgba(227,75,45,.24)';c.shadowBlur=18;c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke();c.shadowBlur=7;c.shadowColor='rgba(227,75,45,.45)';c.strokeStyle='rgba(235,89,55,.96)';c.lineWidth=w;c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke();c.shadowBlur=0;c.strokeStyle='rgba(255,239,217,.84)';c.lineWidth=Math.max(1,w*.22);c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke();c.restore()}
  drawNewSegments(){if(this.analysis||this.points.length<2)return;for(let i=Math.max(1,this.liveIndex);i<this.points.length;i++)this.segment(this.points[i-1],this.points[i]);this.liveIndex=this.points.length;const z=this.points.at(-1),c=this.ctx;c.save();c.fillStyle='#fff1dc';c.shadowColor='#e34b2d';c.shadowBlur=19;c.beginPath();c.arc(z.x,z.y,2.8,0,TAU);c.fill();c.restore()}
  redrawLive(){this.clear();this.liveIndex=1;this.drawNewSegments()}
  finish(a,target=null){this.analysis=a;this.target=target;this.drawResult()}
  drawResult(){if(!this.analysis)return;const a=this.analysis,c=this.ctx,p=a.sampled,f=a.fit,t=this.target||{left:innerWidth*.49,top:innerHeight*.13,width:innerWidth*.48,height:innerWidth*.48},cx=t.left+t.width*.5,cy=t.top+t.height*.5,tr=Math.min(t.width,t.height)*.34,scale=tr/f.r,map=q=>({x:cx+(q.x-f.cx)*scale,y:cy+(q.y-f.cy)*scale});this.clear();c.save();c.lineCap='round';c.lineJoin='round';c.strokeStyle='rgba(233,227,214,.2)';c.lineWidth=1;c.setLineDash([4,7]);c.beginPath();c.arc(cx,cy,tr,0,TAU);c.stroke();c.setLineDash([]);const step=3;c.strokeStyle='rgba(227,75,45,.22)';c.lineWidth=.7;for(let i=0;i<p.length;i+=step){const q=map(p[i]),ang=Math.atan2(p[i].y-f.cy,p[i].x-f.cx),ix=cx+Math.cos(ang)*tr,iy=cy+Math.sin(ang)*tr;c.beginPath();c.moveTo(ix,iy);c.lineTo(q.x,q.y);c.stroke()}for(let i=1;i<p.length;i++){const q=map(p[i-1]),z=map(p[i]),d=clamp(Math.abs(a.deviations[i]||0)/(f.r*.08));c.shadowColor='rgba(227,75,45,.24)';c.shadowBlur=7;c.strokeStyle=d>.55?'rgba(227,75,45,.98)':'rgba(233,227,214,.94)';c.lineWidth=2.1;c.beginPath();c.moveTo(q.x,q.y);c.lineTo(z.x,z.y);c.stroke()}c.shadowBlur=0;c.fillStyle='#e34b2d';c.beginPath();c.arc(cx,cy,2,0,TAU);c.fill();c.restore()}
}
export class SoundEngine{constructor(){this.ctx=null;this.enabled=true}ensure(){if(!this.enabled)return null;try{if(!this.ctx)this.ctx=new AudioContext();if(this.ctx.state==='suspended')this.ctx.resume();return this.ctx}catch{return null}}tone(freq,d=.16,g=.018,type='sine',delay=0){const c=this.ensure();if(!c)return;const o=c.createOscillator(),v=c.createGain();o.type=type;o.frequency.value=freq;v.gain.setValueAtTime(.0001,c.currentTime+delay);v.gain.exponentialRampToValueAtTime(g,c.currentTime+delay+.018);v.gain.exponentialRampToValueAtTime(.0001,c.currentTime+delay+d);o.connect(v);v.connect(c.destination);o.start(c.currentTime+delay);o.stop(c.currentTime+delay+d+.03)}begin(){this.tone(146.8,.28,.018);this.tone(220,.3,.012,'sine',.06)}pen(){this.tone(698,.045,.006,'triangle')}result(s){const r=s>97?220:196;this.tone(r,.3,.018);this.tone(r*1.5,.36,.012,'sine',.07);this.tone(r*2,.42,.008,'sine',.14)}}
