import{FieldRenderer,DrawingRenderer,SoundEngine,ease,TAU}from'./engine.js';
import{analyze}from'./scoring.js';
const $=id=>document.getElementById(id),intro=$('intro'),ready=$('ready'),result=$('result'),begin=$('beginButton'),again=$('againButton'),share=$('shareButton'),brand=$('brandButton'),soundBtn=$('soundButton'),best=$('bestBadge'),hud=$('drawHud'),count=$('pointCount'),toast=$('toast'),scoreEl=$('scoreValue'),verdict=$('verdict'),note=$('resultNote'),mc=$('mCircularity'),mcl=$('mClosure'),ms=$('mSymmetry'),mf=$('mFlow'),pb=$('personalBest');
const field=new FieldRenderer($('field')),draw=new DrawingRenderer($('draw')),sound=new SoundEngine();let mode='intro',pointer=null,current=null,timer=0;
const vibrate=p=>{try{navigator.vibrate?.(p)}catch{}};
function setMode(x){mode=x;intro.classList.toggle('is-active',x==='intro');ready.classList.toggle('is-active',x==='ready');result.classList.toggle('is-active',x==='result');hud.classList.toggle('is-visible',x==='drawing');field.setEnergy(x==='drawing'?.78:x==='result'?.46:.22)}
function msg(t){toast.textContent=t;toast.classList.add('is-visible');clearTimeout(timer);timer=setTimeout(()=>toast.classList.remove('is-visible'),1800)}
function loadBest(){const v=+localStorage.getItem('circle.best');if(v){best.hidden=false;best.querySelector('strong').textContent=v.toFixed(3)+'%'}}
function saveBest(v){const old=+localStorage.getItem('circle.best');pb.hidden=!(v>old);if(v>old)localStorage.setItem('circle.best',v.toFixed(3));loadBest()}
function reset(){current=null;draw.reset();setMode('ready')}
begin.onclick=()=>{sound.begin();vibrate(12);reset()};again.onclick=()=>{sound.begin();vibrate(10);reset()};brand.onclick=()=>{draw.reset();current=null;setMode('intro')};soundBtn.onclick=()=>{sound.enabled=!sound.enabled;soundBtn.setAttribute('aria-pressed',sound.enabled);if(sound.enabled)sound.pen()};
const pt=e=>({x:e.clientX,y:e.clientY,t:performance.now(),p:e.pressure||.5});
addEventListener('pointerdown',e=>{field.setPointer(e.clientX,e.clientY);if(mode!=='ready'||e.target.closest?.('button'))return;e.preventDefault();pointer=e.pointerId;setMode('drawing');draw.reset();draw.start(pt(e));sound.pen();vibrate(8)},{passive:false});
addEventListener('pointermove',e=>{field.setPointer(e.clientX,e.clientY);if(mode!=='drawing'||pointer!==e.pointerId)return;e.preventDefault();for(const q of(e.getCoalescedEvents?.()||[e]))draw.add(pt(q));count.textContent=String(draw.points.length).padStart(3,'0').slice(-3)},{passive:false});
function finish(e){if(mode!=='drawing'||pointer!==e.pointerId)return;pointer=null;draw.add(pt(e));const a=analyze(draw.points);if(!a){vibrate([15,40,15]);msg('DRAW A LARGER, COMPLETE LOOP');setTimeout(reset,420);return}current=a;draw.finish(a);setMode('result');saveBest(a.score);sound.result(a.score);vibrate(a.score>95?[15,35,25]:18);show(a)}
addEventListener('pointerup',finish,{passive:false});addEventListener('pointercancel',e=>{if(pointer===e.pointerId){pointer=null;reset()}});
function num(el,to,d=900,digits=1){const s=performance.now(),tick=n=>{const t=ease((n-s)/d);el.textContent=(to*t).toFixed(digits);if(t<1)requestAnimationFrame(tick)};requestAnimationFrame(tick)}
function show(a){scoreEl.textContent='0.000';verdict.textContent=a.verdict;note.textContent=a.note;mc.textContent=mcl.textContent=ms.textContent=mf.textContent='—';setTimeout(()=>num(scoreEl,a.score,1150,3),120);setTimeout(()=>{num(mc,a.circularity,700);num(mcl,a.closure,700);num(ms,a.symmetry,700);num(mf,a.flow,700)},430)}
function card(a){return new Promise((resolve,reject)=>{const c=document.createElement('canvas');c.width=1080;c.height=1350;const x=c.getContext('2d'),g=x.createRadialGradient(760,420,0,760,420,780);g.addColorStop(0,'#25203a');g.addColorStop(.52,'#0f0e16');g.addColorStop(1,'#070709');x.fillStyle=g;x.fillRect(0,0,1080,1350);x.strokeStyle='rgba(184,255,234,.16)';x.lineWidth=26;x.beginPath();x.arc(740,470,265,0,TAU);x.stroke();const scale=Math.min(265/a.fit.r,.95);x.save();x.translate((740-a.fit.cx)*scale+(1-scale)*740,(470-a.fit.cy)*scale+(1-scale)*470);x.scale(scale,scale);x.lineCap=x.lineJoin='round';x.strokeStyle='#f4f0e8';x.lineWidth=3/scale;x.beginPath();x.moveTo(a.points[0].x,a.points[0].y);for(let i=1;i<a.points.length;i++)x.lineTo(a.points[i].x,a.points[i].y);x.stroke();x.restore();x.fillStyle='#f4f0e8';x.font='600 34px Arial';x.fillText('CÍRCLE',80,105);x.fillStyle='rgba(244,240,232,.46)';x.font='700 18px Arial';x.fillText('DRAW PERFECTION.',80,780);x.fillStyle='#f4f0e8';x.font='600 150px Arial';x.fillText(a.score.toFixed(3)+'%',72,960);x.font='500 44px Arial';x.fillText(a.verdict,80,1035);x.fillStyle='rgba(244,240,232,.4)';x.font='500 20px Arial';x.fillText('CIRCULARITY   CLOSURE   SYMMETRY   FLOW',80,1150);x.fillStyle='#f4f0e8';x.font='500 28px Arial';x.fillText(`${a.circularity.toFixed(1)}        ${a.closure.toFixed(1)}        ${a.symmetry.toFixed(1)}        ${a.flow.toFixed(1)}`,80,1197);x.fillStyle='rgba(244,240,232,.25)';x.font='500 18px Arial';x.fillText('HOW CLOSE CAN YOUR HAND GET?',80,1280);c.toBlob(b=>b?resolve(b):reject(),'image/png',.94)})}
share.onclick=async()=>{if(!current)return;try{const blob=await card(current),file=new File([blob],`circle-${current.score.toFixed(3)}.png`,{type:'image/png'}),text=`I drew a ${current.score.toFixed(3)}% circle. Can you beat it?`;if(navigator.canShare?.({files:[file]})){await navigator.share({title:'CÍRCLE',text,files:[file]})}else if(navigator.share){await navigator.share({title:'CÍRCLE',text,url:location.href})}else{await navigator.clipboard.writeText(location.href+' — '+current.score.toFixed(3)+'%');msg('RESULT LINK COPIED')}}catch(e){if(e?.name!=='AbortError')msg('SHARING NOT AVAILABLE')}};
addEventListener('resize',()=>{field.resize();draw.resize();if(current)draw.finish(current)});addEventListener('mousemove',e=>field.setPointer(e.clientX,e.clientY),{passive:true});document.querySelectorAll('.magnetic').forEach(el=>{el.addEventListener('pointermove',e=>{if(matchMedia('(pointer:coarse)').matches)return;const r=el.getBoundingClientRect(),x=(e.clientX-r.left-r.width/2)*.12,y=(e.clientY-r.top-r.height/2)*.12;el.style.transform=`translate(${x}px,${y}px)`});el.addEventListener('pointerleave',()=>el.style.transform='')});
function loop(n){field.render(n);draw.render(n);requestAnimationFrame(loop)}loadBest();if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));requestAnimationFrame(loop);
