import{DrawingRenderer,SoundEngine,ease,TAU}from'./engine.js';
import{analyze}from'./scoring.js';
const $=id=>document.getElementById(id),body=document.body,intro=$('intro'),ready=$('ready'),result=$('result'),start=$('startButton'),again=$('againButton'),share=$('shareButton'),home=$('homeButton'),best=$('bestBadge'),hud=$('traceHud'),count=$('pointCount'),toast=$('toast'),scoreEl=$('scoreValue'),verdict=$('verdict'),note=$('resultNote'),mc=$('mCircularity'),mcl=$('mClosure'),ms=$('mSymmetry'),mf=$('mFlow'),newBest=$('newBest'),runLabel=$('runLabel');
const draw=new DrawingRenderer($('draw')),sound=new SoundEngine();let mode='intro',activePointer=null,current=null,runs=0,timer=0;
const vibrate=p=>{try{navigator.vibrate?.(p)}catch{}};
function setMode(next){mode=next;body.dataset.mode=next;body.classList.toggle('is-drawing',next==='drawing');intro.classList.toggle('is-active',next==='intro');ready.classList.toggle('is-active',next==='ready');result.classList.toggle('is-active',next==='result');hud.classList.toggle('is-visible',next==='drawing')}
function msg(text){toast.textContent=text;toast.classList.add('is-visible');clearTimeout(timer);timer=setTimeout(()=>toast.classList.remove('is-visible'),1500)}
function loadBest(){const v=+localStorage.getItem('circle.best.v5');if(v){best.hidden=false;best.querySelector('b').textContent=v.toFixed(3)+'%'}}
function saveBest(v){const old=+localStorage.getItem('circle.best.v5');newBest.hidden=!(v>old);if(v>old)localStorage.setItem('circle.best.v5',v.toFixed(3));loadBest()}
function reset(){current=null;draw.reset();count.textContent='000';setMode('ready')}
start.onclick=()=>{sound.begin();vibrate(8);reset()};again.onclick=()=>{sound.begin();vibrate(7);reset()};home.onclick=()=>{activePointer=null;current=null;draw.reset();setMode('intro')};
const point=e=>({x:e.clientX,y:e.clientY,t:performance.now(),p:e.pressure||.5});
addEventListener('pointerdown',e=>{if(mode!=='ready'||e.target.closest?.('button'))return;e.preventDefault();activePointer=e.pointerId;draw.reset();draw.start(point(e));setMode('drawing');sound.pen();vibrate(5)},{passive:false});
addEventListener('pointermove',e=>{if(mode!=='drawing'||activePointer!==e.pointerId)return;e.preventDefault();const list=e.getCoalescedEvents?.()||[e];for(const q of list)draw.add(point(q));count.textContent=String(draw.points.length).padStart(3,'0').slice(-3)},{passive:false});
function finish(e){if(mode!=='drawing'||activePointer!==e.pointerId)return;e.preventDefault();activePointer=null;draw.add(point(e));const a=analyze(draw.points);if(!a){vibrate([8,24,8]);msg('DRAW ONE LARGER CLOSED LOOP');setTimeout(reset,280);return}current=a;runs++;draw.finish(a);setMode('result');saveBest(a.score);sound.result(a.score);vibrate(a.score>95?[9,20,15]:10);show(a)}
addEventListener('pointerup',finish,{passive:false});addEventListener('pointercancel',e=>{if(e.pointerId===activePointer){activePointer=null;reset()}});
function animateNumber(el,to,duration=760,digits=1){const s=performance.now();function tick(n){const t=ease((n-s)/duration);el.textContent=(to*t).toFixed(digits);if(t<1)requestAnimationFrame(tick)}requestAnimationFrame(tick)}
function show(a){runLabel.textContent='RUN / '+String(runs).padStart(3,'0');scoreEl.textContent='0.000';verdict.textContent=a.verdict.replace(/\.$/,'');note.textContent=a.note;mc.textContent=mcl.textContent=ms.textContent=mf.textContent='—';setTimeout(()=>animateNumber(scoreEl,a.score,900,3),70);setTimeout(()=>{animateNumber(mc,a.circularity,560);animateNumber(mcl,a.closure,560);animateNumber(ms,a.symmetry,560);animateNumber(mf,a.flow,560)},230)}
function makeCard(a){return new Promise((resolve,reject)=>{const c=document.createElement('canvas');c.width=1080;c.height=1350;const x=c.getContext('2d'),g=x.createRadialGradient(760,360,0,760,360,860);g.addColorStop(0,'#19213a');g.addColorStop(.42,'#0b0e18');g.addColorStop(1,'#05060a');x.fillStyle=g;x.fillRect(0,0,c.width,c.height);x.strokeStyle='rgba(255,255,255,.08)';x.lineWidth=1;x.beginPath();x.arc(720,430,270,0,TAU);x.stroke();const scale=Math.min(260/a.fit.r,.96);x.save();x.translate(720-a.fit.cx*scale,430-a.fit.cy*scale);x.scale(scale,scale);x.lineCap=x.lineJoin='round';for(let i=1;i<a.points.length;i++){const q=a.points[i-1],z=a.points[i],d=Math.min(1,Math.abs(a.deviations[i]||0)/(a.fit.r*.085));x.strokeStyle=d>.52?'#a778ff':'#73f7ff';x.globalAlpha=.82+.18*d;x.lineWidth=2.3/scale;x.beginPath();x.moveTo(q.x,q.y);x.lineTo(z.x,z.y);x.stroke()}x.restore();x.fillStyle='#f5f7fb';x.font='700 27px Arial';x.fillText('CÍRCLE / DRAW THE IMPOSSIBLE',70,82);x.fillStyle='rgba(245,247,251,.45)';x.font='700 16px monospace';x.fillText('GEOMETRIC FIDELITY',70,835);x.fillStyle='#f5f7fb';x.font='700 148px Arial';x.fillText(a.score.toFixed(3),60,1010);x.fillStyle='#64f7ff';x.font='300 52px Arial';x.fillText('%',770,920);x.fillStyle='#f5f7fb';x.font='italic 45px Georgia';x.fillText(a.verdict.replace(/\.$/,''),70,1090);x.fillStyle='rgba(245,247,251,.45)';x.font='700 17px monospace';x.fillText(`RADIAL ${a.circularity.toFixed(1)}   CLOSURE ${a.closure.toFixed(1)}   SYMMETRY ${a.symmetry.toFixed(1)}   FLOW ${a.flow.toFixed(1)}`,70,1185);x.fillText('ONE STROKE. NO GUIDE.',70,1280);c.toBlob(b=>b?resolve(b):reject(),'image/png',.93)})}
share.onclick=async()=>{if(!current)return;try{const blob=await makeCard(current),file=new File([blob],`circle-${current.score.toFixed(3)}.png`,{type:'image/png'}),text=`${current.score.toFixed(3)}% geometric fidelity. Can you beat it?`;if(navigator.canShare?.({files:[file]}))await navigator.share({title:'CÍRCLE',text,files:[file]});else if(navigator.share)await navigator.share({title:'CÍRCLE',text,url:location.href});else{await navigator.clipboard.writeText(`${text} ${location.href}`);msg('LINK COPIED')}}catch(e){if(e?.name!=='AbortError')msg('SHARING UNAVAILABLE')}};
addEventListener('resize',()=>draw.resize(),{passive:true});
loadBest();
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=5',{updateViaCache:'none'}).catch(()=>{}));
