const TAU=Math.PI*2,clamp=(v,a=0,b=1)=>Math.min(b,Math.max(a,v)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
function pathLength(p){let s=0;for(let i=1;i<p.length;i++)s+=dist(p[i-1],p[i]);return s}
function resample(points,n=360){if(points.length<2)return points.slice();const cum=[0];for(let i=1;i<points.length;i++)cum.push(cum.at(-1)+dist(points[i-1],points[i]));const total=cum.at(-1);if(total<1)return points.slice();const out=[];let j=1;for(let k=0;k<n;k++){const target=total*k/(n-1);while(j<cum.length-1&&cum[j]<target)j++;const a=points[j-1],b=points[j],span=Math.max(1e-9,cum[j]-cum[j-1]),t=(target-cum[j-1])/span;out.push({x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t,t:a.t+(b.t-a.t)*t,p:(a.p||.5)+((b.p||.5)-(a.p||.5))*t})}return out}
function solve3(A,b){const m=A.map((r,i)=>[...r,b[i]]);for(let i=0;i<3;i++){let k=i;for(let q=i+1;q<3;q++)if(Math.abs(m[q][i])>Math.abs(m[k][i]))k=q;[m[i],m[k]]=[m[k],m[i]];if(Math.abs(m[i][i])<1e-12)return null;const d=m[i][i];for(let j=i;j<4;j++)m[i][j]/=d;for(let q=0;q<3;q++)if(q!==i){const f=m[q][i];for(let j=i;j<4;j++)m[q][j]-=f*m[i][j]}}return[m[0][3],m[1][3],m[2][3]]}
function fitGeometric(p){let cx=p.reduce((s,q)=>s+q.x,0)/p.length,cy=p.reduce((s,q)=>s+q.y,0)/p.length,r=p.reduce((s,q)=>s+Math.hypot(q.x-cx,q.y-cy),0)/p.length;for(let iter=0;iter<10;iter++){const J=[[0,0,0],[0,0,0],[0,0,0]],g=[0,0,0];for(const q of p){const dx=cx-q.x,dy=cy-q.y,d=Math.max(1e-8,Math.hypot(dx,dy)),e=d-r,v=[dx/d,dy/d,-1];for(let a=0;a<3;a++){g[a]+=v[a]*e;for(let b=0;b<3;b++)J[a][b]+=v[a]*v[b]}}const delta=solve3(J,g.map(v=>-v));if(!delta)break;cx+=delta[0];cy+=delta[1];r+=delta[2];if(Math.hypot(delta[0],delta[1])+Math.abs(delta[2])<1e-5)break}return r>0&&Number.isFinite(r)?{cx,cy,r}:null}
function smooth(p,radius=2){return p.map((q,i)=>{let x=0,y=0,n=0;for(let k=Math.max(0,i-radius);k<=Math.min(p.length-1,i+radius);k++){x+=p[k].x;y+=p[k].y;n++}return{...q,x:x/n,y:y/n}})}
function coverage(p,f){let total=0,prev=Math.atan2(p[0].y-f.cy,p[0].x-f.cx);for(let i=1;i<p.length;i++){const a=Math.atan2(p[i].y-f.cy,p[i].x-f.cx);let d=a-prev;while(d>Math.PI)d-=TAU;while(d<-Math.PI)d+=TAU;total+=d;prev=a}return Math.abs(total)/TAU}
function pct(v){return Math.max(0,v*100)}
export function analyze(points){if(points.length<45)return null;const raw=points.filter((p,i)=>!i||dist(p,points[i-1])>.25);if(raw.length<45)return null;const sampledRaw=resample(raw,360),sampled=smooth(sampledRaw,2),f=fitGeometric(sampled);if(!f||f.r<52)return null;const deviations=sampled.map(q=>Math.hypot(q.x-f.cx,q.y-f.cy)-f.r),radialRms=Math.sqrt(deviations.reduce((s,v)=>s+v*v,0)/deviations.length)/f.r,closureGap=dist(sampledRaw[0],sampledRaw.at(-1))/(2*f.r),cov=coverage(sampledRaw,f),coverageError=Math.abs(1-cov),lengthRatio=pathLength(sampled)/(TAU*f.r),pathExcess=Math.max(0,lengthRatio-1),sizePenalty=f.r<72?(72-f.r)/72:0,loopPenalty=cov>1.28?(cov-1.28)*.7:0;
  // Score is 100 minus normalized geometric error. Radial RMS is the dominant term; closure, angular coverage and excess path prevent open arcs/jagged loops from scoring as perfect circles.
  const normalizedError=radialRms + .34*closureGap + .24*coverageError + .18*pathExcess + .35*sizePenalty + loopPenalty;
  const score=normalizedError<5e-5?100:clamp(100*(1-normalizedError),0,100);
  const radialPct=pct(radialRms),closurePct=clamp(100*(1-closureGap),0,100),coveragePct=clamp(100*(1-coverageError),0,100),pathPct=pct(pathExcess);
  let band='organic';if(score>=99.5)band='anomaly';else if(score>=98)band='rare';else if(score>=95)band='precise';else if(score>=90)band='close';else if(score>=80)band='human';
  return{score,band,fit:f,sampled,deviations,radialRms,radialPct,closureGap,closurePct,coverage:cov,coveragePct,pathExcess,pathPct,lengthRatio,points:[...raw]}}
