plugins {
    id 'com.android.application'
}

android {
    namespace = 'io.ceskasc.ocircle'
    compileSdk = 36

    defaultConfig {
        applicationId = 'io.ceskasc.ocircle'
        minSdk = 26
        targetSdk = 36
        versionCode = 9
        versionName = '13.5'
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    buildTypes {
        debug {
            debuggable = true
        }
        release {
            minifyEnabled = false
        }
    }
}
